Fix linting

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -5,8 +5,8 @@ set -o pipefail
 
 ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version  }
 TMPDIR=${TMPDIR:-/tmp}
-[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
-[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
+[ -n "$ASDF_INSTALL_VERSION" ] || (echo >&2 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (echo >&2 'Missing ASDF_INSTALL_PATH' && exit 1)
 
 install_goreleaser() {
   local install_type
@@ -41,18 +41,18 @@ install_goreleaser() {
 get_arch() {
   arch=$(uname -m | tr '[:upper:]' '[:lower:]')
   case ${arch} in
-  arm64)
-    arch='arm64'
-    ;;
-  arm6)
-    arch='arm6'
-    ;;
-  x86_64)
-    arch='x86_64'
-    ;;
-  i386)
-    arch='i386'
-    ;;
+    arm64)
+      arch='arm64'
+      ;;
+    arm6)
+      arch='arm6'
+      ;;
+    x86_64)
+      arch='x86_64'
+      ;;
+    i386)
+      arch='i386'
+      ;;
   esac
 
   echo ${arch}
@@ -61,15 +61,15 @@ get_arch() {
 get_platform() {
   plat=$(uname | tr '[:upper:]' '[:lower:]')
   case ${plat} in
-  darwin)
-    plat='Darwin'
-    ;;
-  linux)
-    plat='Linux'
-    ;;
-  windows)
-    plat='Windows'
-    ;;
+    darwin)
+      plat='Darwin'
+      ;;
+    linux)
+      plat='Linux'
+      ;;
+    windows)
+      plat='Windows'
+      ;;
   esac
 
   echo ${plat}
@@ -78,11 +78,12 @@ get_platform() {
 get_ext() {
   plat=$(uname | tr '[:upper:]' '[:lower:]')
   case ${plat} in
-  windows)
-    ext='zip'
-    ;;
-  *)
-    ext='tar.gz'
+    windows)
+      ext='zip'
+      ;;
+    *)
+      ext='tar.gz'
+      ;;
   esac
 
   echo ${ext}
@@ -101,4 +102,3 @@ get_download_url() {
 }
 
 install_goreleaser "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
-
